Update xtermjs and socketio
cs01/pyxtermjs pull request #18
Opened 2021-05-01 15:58 UTC by manics

Thanks for creating this project as a learning resource. I thought I'd update the dependencies:
- xterm 4.11.0
- socket.io 4.0.1
- flask-socketio 5

2021-05-01 15:58 UTC, manics commented on pyxtermjs/index.html
> -<script src="https://unpkg.com/xterm@3.6.0/dist/addons/fullscreen/fullscreen.js"></script>
The fullscreen addon is no longer supported

2021-05-20 05:47 UTC, cs01 commented
Thanks for this! It will definitely be good to keep the "bit rot" off this as much as possible.

I tried it out with
```
python3.7 -m venv venv
source venv/bin/activate
pip install -r requirements.txt 
python -m pyxtermjs
```
but in the browser, the state remains on "connecting" and the terminal doesn't work. Could you provide steps to reproduce it working?

2021-05-20 19:26 UTC, cs01 requested changes
Could not get this branch to run in my computer

2021-06-03 21:11 UTC, manics commented
Sorry for the delay in responding. I've tested this again just now:
```
conda create -n tmp python=3.7
conda activate tmp
pip install -r requirements.txt 
pip install .
python -m pyxtermjs
```
http://127.0.0.1:5000/ loads successfully. I've tried this in Firefox 88.0 and Chrome 90.0.4430.93 on Fedora Linux 33.

2021-08-11 03:08 UTC, cs01 commented
> Sorry for the delay in responding.

I too am sorry for my delayed reply :). I tried out your change again, and it worked. I think the fix is to update `setup.py` to install from requirements.txt. I'll merge your change as-is and then fix setup.py some more.

2021-08-11 03:08 UTC, merged